"""PostgreSQL coverage for table fixture loading and export."""

import json
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest

from sqlspec.utils.fixtures import (
    export_table_fixtures_async,
    export_table_fixtures_sync,
    load_table_fixtures_async,
    load_table_fixtures_sync,
)

if TYPE_CHECKING:
    from sqlspec.adapters.asyncpg import AsyncpgDriver
    from sqlspec.adapters.psycopg import PsycopgSyncConfig

pytestmark = pytest.mark.xdist_group("postgres")

SETUP_SQL = """
DROP SCHEMA IF EXISTS fixture_resync CASCADE;
CREATE SCHEMA fixture_resync;
CREATE TABLE fixture_resync.serial_items (id SERIAL PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE fixture_resync.identity_items (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE fixture_resync.empty_items (id SERIAL PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE fixture_resync.plain_items (id INTEGER PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE fixture_resync.min_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100 MINVALUE 100) PRIMARY KEY, name TEXT NOT NULL
);
CREATE TABLE fixture_resync.always_items (id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE fixture_resync."MixedItems" (id SERIAL PRIMARY KEY, "userName" TEXT NOT NULL);
CREATE TABLE fixture_resync.always_upsert (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL
);
CREATE TABLE fixture_resync."user" (id INTEGER PRIMARY KEY, "order" INTEGER NOT NULL, "group" TEXT NOT NULL);
CREATE TABLE fixture_resync.typed_items (
    id INTEGER PRIMARY KEY,
    created_at TIMESTAMPTZ,
    local_at TIMESTAMP,
    day DATE,
    at_time TIME,
    amount NUMERIC(12, 4),
    token UUID,
    payload BYTEA,
    document JSONB,
    tags JSONB,
    note JSON,
    scores INTEGER[],
    active BOOLEAN
);
INSERT INTO fixture_resync.typed_items VALUES
    (1, '2024-01-02 03:04:05.123456+00', '2024-01-02 03:04:05', '2024-01-02', '03:04:05.5', 12.3450,
     '7f3c1d2e-9a4b-4c5d-8e6f-0a1b2c3d4e5f', '\\x00ff10', '{"a": {"b": [1, "x"]}}', '[1, "two", null]', '"text"',
     '{1,2,3}', true),
    (2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
CREATE TABLE fixture_resync.generated_items (
    id INTEGER PRIMARY KEY,
    doubled INTEGER GENERATED ALWAYS AS (id * 2) STORED,
    span INTERVAL,
    at_timetz TIME WITH TIME ZONE
);
INSERT INTO fixture_resync.generated_items (id, span, at_timetz) VALUES
    (1, '1 day 02:03:04.5', '03:04:05+02'),
    (2, '-00:00:01', '23:59:59-05:30'),
    (3, NULL, NULL);
CREATE TABLE fixture_resync.unkeyed_items (id INTEGER, docs JSON[], spots POINT[]);
INSERT INTO fixture_resync.unkeyed_items VALUES (2, ARRAY['{"a": 1}'::json], ARRAY[point(1, 2)]), (1, NULL, NULL);
"""
TEARDOWN_SQL = "DROP SCHEMA IF EXISTS fixture_resync CASCADE"
SELECT_GENERATED_SQL = "SELECT * FROM fixture_resync.generated_items ORDER BY id"
ROWS = [{"id": row_id, "name": f"item {row_id}"} for row_id in range(1, 6)]
SELECT_TYPED_SQL = "SELECT * FROM fixture_resync.typed_items ORDER BY id"
RESYNC_TABLES = (
    "fixture_resync.serial_items",
    "fixture_resync.identity_items",
    "fixture_resync.plain_items",
    "fixture_resync.always_items",
    "fixture_resync.empty_items",
    "fixture_resync.min_items",
    "fixture_resync.MixedItems",
)


def _write_rows(fixtures_path: Path, table: str, rows: "list[dict[str, Any]]") -> None:
    fixtures_path.mkdir(parents=True, exist_ok=True)
    (fixtures_path / f"{table}.json").write_text(json.dumps(rows), encoding="utf-8")


def _write_resync_fixtures(fixtures_path: Path) -> None:
    for table in RESYNC_TABLES[:4]:
        _write_rows(fixtures_path, table, ROWS)
    _write_rows(fixtures_path, "fixture_resync.empty_items", [])
    _write_rows(fixtures_path, "fixture_resync.min_items", [])
    _write_rows(fixtures_path, "fixture_resync.MixedItems", [{"id": 7, "userName": "Ann"}])


async def test_resync_sequences(asyncpg_async_driver: "AsyncpgDriver", tmp_path: Path) -> None:
    """Serial and identity sequences continue after the loaded ids or restart at their minimum."""
    _write_resync_fixtures(tmp_path)
    driver = asyncpg_async_driver
    await driver.execute_script(SETUP_SQL)
    try:
        counts = await load_table_fixtures_async(driver, tmp_path, tables=RESYNC_TABLES, resync_sequences=True)

        assert counts["fixture_resync.serial_items"] == 5
        assert counts["fixture_resync.always_items"] == 5
        for table in ("serial_items", "identity_items"):
            new_id = await driver.select_value(
                f"INSERT INTO fixture_resync.{table} (name) VALUES ('next') RETURNING id"
            )
            assert new_id == 6
        assert (
            await driver.select_value("INSERT INTO fixture_resync.always_items (name) VALUES ('next') RETURNING id")
            == 6
        )
        assert await driver.select_value("INSERT INTO fixture_resync.empty_items (name) VALUES ('x') RETURNING id") == 1
        assert await driver.select_value("INSERT INTO fixture_resync.min_items (name) VALUES ('x') RETURNING id") == 100
        assert (
            await driver.select_value(
                'INSERT INTO fixture_resync."MixedItems" ("userName") VALUES (\'x\') RETURNING id'
            )
            == 8
        )
    finally:
        await driver.execute_script(TEARDOWN_SQL)


def test_resync_sequences_sync(psycopg_sync_config: "PsycopgSyncConfig", tmp_path: Path) -> None:
    """The sync loader resyncs serial and identity sequences."""
    _write_resync_fixtures(tmp_path)
    with psycopg_sync_config.provide_session() as driver:
        driver.execute_script(SETUP_SQL)
        try:
            load_table_fixtures_sync(driver, tmp_path, tables=RESYNC_TABLES, resync_sequences=True)

            for table in ("serial_items", "identity_items", "always_items"):
                new_id = driver.select_value(f"INSERT INTO fixture_resync.{table} (name) VALUES ('next') RETURNING id")
                assert new_id == 6
            assert driver.select_value("INSERT INTO fixture_resync.empty_items (name) VALUES ('x') RETURNING id") == 1
            assert driver.select_value("INSERT INTO fixture_resync.min_items (name) VALUES ('x') RETURNING id") == 100
        finally:
            driver.execute_script(TEARDOWN_SQL)


async def test_unqualified_tables_resolve_through_search_path(
    asyncpg_async_driver: "AsyncpgDriver", tmp_path: Path
) -> None:
    """Unqualified table names resolve through the session search_path, including resync."""
    _write_rows(tmp_path, "serial_items", ROWS)
    driver = asyncpg_async_driver
    await driver.execute_script(SETUP_SQL)
    try:
        await driver.execute_script("SET search_path TO public, fixture_resync")

        counts = await load_table_fixtures_async(driver, tmp_path, resync_sequences=True)

        assert counts == {"serial_items": 5}
        assert await driver.select_value("INSERT INTO serial_items (name) VALUES ('next') RETURNING id") == 6
    finally:
        await driver.execute_script(f"RESET search_path; {TEARDOWN_SQL}")


async def test_reserved_and_mixed_case_identifiers(asyncpg_async_driver: "AsyncpgDriver", tmp_path: Path) -> None:
    """Reserved-word tables and columns and mixed-case names keep their exact spelling."""
    driver = asyncpg_async_driver
    await driver.execute_script(SETUP_SQL)
    try:
        _write_rows(tmp_path, "fixture_resync.user", [{"id": 1, "order": 2, "group": "a"}])
        _write_rows(tmp_path, "fixture_resync.MixedItems", [{"id": 1, "userName": "Ann"}])
        await load_table_fixtures_async(driver, tmp_path)
        _write_rows(tmp_path, "fixture_resync.user", [{"id": 1, "order": 3, "group": "b"}])
        _write_rows(tmp_path, "fixture_resync.MixedItems", [{"id": 1, "userName": "Bea"}])

        await load_table_fixtures_async(
            driver, tmp_path, conflict_keys={"fixture_resync.user": ["id"], "fixture_resync.MixedItems": ["id"]}
        )
        written = await export_table_fixtures_async(
            driver, tmp_path / "out", ["fixture_resync.user", "fixture_resync.MixedItems"], compress=False
        )

        assert written == {"fixture_resync.user": 1, "fixture_resync.MixedItems": 1}
        assert json.loads((tmp_path / "out" / "fixture_resync.user.json").read_text()) == [
            {"id": 1, "order": 3, "group": "b"}
        ]
        assert json.loads((tmp_path / "out" / "fixture_resync.MixedItems.json").read_text()) == [
            {"id": 1, "userName": "Bea"}
        ]
    finally:
        await driver.execute_script(TEARDOWN_SQL)


@pytest.mark.parametrize("jsonl", [False, True])
async def test_export_load_roundtrip_typed_columns_asyncpg(
    asyncpg_async_driver: "AsyncpgDriver", tmp_path: Path, jsonl: bool
) -> None:
    """Temporal, numeric, uuid, bytea, json, and array columns round-trip through asyncpg."""
    driver = asyncpg_async_driver
    await driver.execute_script(SETUP_SQL)
    try:
        before = await driver.select(SELECT_TYPED_SQL)

        await export_table_fixtures_async(driver, tmp_path, ["fixture_resync.typed_items"], jsonl=jsonl)
        await driver.execute("DELETE FROM fixture_resync.typed_items")
        counts = await load_table_fixtures_async(driver, tmp_path)

        assert counts == {"fixture_resync.typed_items": 2}
        assert await driver.select(SELECT_TYPED_SQL) == before
    finally:
        await driver.execute_script(TEARDOWN_SQL)


@pytest.mark.parametrize("jsonl", [False, True])
def test_export_load_roundtrip_typed_columns_psycopg(
    psycopg_sync_config: "PsycopgSyncConfig", tmp_path: Path, jsonl: bool
) -> None:
    """Temporal, numeric, uuid, bytea, json, and array columns round-trip through psycopg."""
    with psycopg_sync_config.provide_session() as driver:
        driver.execute_script(SETUP_SQL)
        try:
            before = driver.select(SELECT_TYPED_SQL)

            export_table_fixtures_sync(driver, tmp_path, ["fixture_resync.typed_items"], jsonl=jsonl)
            driver.execute("DELETE FROM fixture_resync.typed_items")
            counts = load_table_fixtures_sync(driver, tmp_path, conflict_keys={"fixture_resync.typed_items": ["id"]})

            assert counts == {"fixture_resync.typed_items": 2}
            assert driver.select(SELECT_TYPED_SQL) == before
        finally:
            driver.execute_script(TEARDOWN_SQL)


async def test_upsert_on_non_identity_key_skips_always_identity_columns(
    asyncpg_async_driver: "AsyncpgDriver", tmp_path: Path
) -> None:
    """Upserting on a unique non-identity key updates other columns and leaves GENERATED ALWAYS ids alone."""
    driver = asyncpg_async_driver
    await driver.execute_script(SETUP_SQL)
    try:
        _write_rows(tmp_path, "fixture_resync.always_upsert", [{"id": 10, "email": "a@example.com", "name": "Ann"}])
        await load_table_fixtures_async(driver, tmp_path)
        _write_rows(tmp_path, "fixture_resync.always_upsert", [{"id": 10, "email": "a@example.com", "name": "Bea"}])

        await load_table_fixtures_async(driver, tmp_path, conflict_keys={"fixture_resync.always_upsert": ["email"]})

        rows = await driver.select("SELECT id, email, name FROM fixture_resync.always_upsert")
        assert rows == [{"id": 10, "email": "a@example.com", "name": "Bea"}]
    finally:
        await driver.execute_script(TEARDOWN_SQL)


async def test_generated_interval_and_timetz_columns_round_trip_asyncpg(
    asyncpg_async_driver: "AsyncpgDriver", tmp_path: Path
) -> None:
    """Stored generated columns are skipped, and interval and time with time zone values load back through asyncpg."""
    driver = asyncpg_async_driver
    await driver.execute_script(SETUP_SQL)
    try:
        before = await driver.select(SELECT_GENERATED_SQL)

        await export_table_fixtures_async(
            driver, tmp_path, ["fixture_resync.generated_items", "fixture_resync.unkeyed_items"], compress=False
        )
        exported = json.loads((tmp_path / "fixture_resync.generated_items.json").read_text())
        await driver.execute("DELETE FROM fixture_resync.generated_items")
        await load_table_fixtures_async(driver, tmp_path, tables=["fixture_resync.generated_items"])

        assert all("doubled" not in row for row in exported)
        assert await driver.select(SELECT_GENERATED_SQL) == before
        assert [row["id"] for row in json.loads((tmp_path / "fixture_resync.unkeyed_items.json").read_text())] == [1, 2]
    finally:
        await driver.execute_script(TEARDOWN_SQL)


def test_generated_interval_and_timetz_columns_round_trip_psycopg(
    psycopg_sync_config: "PsycopgSyncConfig", tmp_path: Path
) -> None:
    """Files that include generated column values load and upsert through psycopg."""
    with psycopg_sync_config.provide_session() as driver:
        driver.execute_script(SETUP_SQL)
        try:
            before = driver.select(SELECT_GENERATED_SQL)

            export_table_fixtures_sync(driver, tmp_path, ["fixture_resync.generated_items"])
            driver.execute("DELETE FROM fixture_resync.generated_items")
            load_table_fixtures_sync(driver, tmp_path)
            (tmp_path / "fixture_resync.generated_items.json.gz").unlink()
            _write_rows(
                tmp_path, "fixture_resync.generated_items", [{"id": 1, "doubled": 99, "span": None, "at_timetz": None}]
            )
            load_table_fixtures_sync(driver, tmp_path, conflict_keys={"fixture_resync.generated_items": ["id"]})

            rows = driver.select(SELECT_GENERATED_SQL)
            assert rows[1:] == before[1:]
            assert rows[0] == {"id": 1, "doubled": 2, "span": None, "at_timetz": None}
        finally:
            driver.execute_script(TEARDOWN_SQL)
