"""PostgreSQL sequence resync coverage for table fixture loading."""

import json
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from sqlspec.utils.fixtures import load_table_fixtures_async, load_table_fixtures_sync

if TYPE_CHECKING:
    from sqlspec.adapters.asyncpg import AsyncpgDriver
    from sqlspec.adapters.psycopg import PsycopgSyncConfig

pytestmark = pytest.mark.xdist_group("postgres")

SETUP_SQL = """
DROP SCHEMA IF EXISTS fixture_resync CASCADE;
CREATE SCHEMA fixture_resync;
CREATE TABLE fixture_resync.serial_items (id SERIAL PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE fixture_resync.identity_items (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE fixture_resync.empty_items (id SERIAL PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE fixture_resync.plain_items (id INTEGER PRIMARY KEY, name TEXT NOT NULL);
"""
TEARDOWN_SQL = "DROP SCHEMA IF EXISTS fixture_resync CASCADE"
TABLES = (
    "fixture_resync.serial_items",
    "fixture_resync.identity_items",
    "fixture_resync.empty_items",
    "fixture_resync.plain_items",
)


def _write_fixtures(fixtures_path: Path) -> None:
    rows = [{"id": row_id, "name": f"item {row_id}"} for row_id in range(1, 6)]
    for table in ("fixture_resync.serial_items", "fixture_resync.identity_items", "fixture_resync.plain_items"):
        (fixtures_path / f"{table}.json").write_text(json.dumps(rows), encoding="utf-8")
    (fixtures_path / "fixture_resync.empty_items.json").write_text("[]", encoding="utf-8")


async def test_resync_sequences(asyncpg_async_driver: "AsyncpgDriver", tmp_path: Path) -> None:
    """Serial and identity sequences continue after the loaded ids."""
    _write_fixtures(tmp_path)
    await asyncpg_async_driver.execute_script(SETUP_SQL)
    try:
        counts = await load_table_fixtures_async(asyncpg_async_driver, tmp_path, tables=TABLES, resync_sequences=True)

        assert counts == {
            "fixture_resync.empty_items": 0,
            "fixture_resync.identity_items": 5,
            "fixture_resync.plain_items": 5,
            "fixture_resync.serial_items": 5,
        }
        for table in ("serial_items", "identity_items"):
            new_id = await asyncpg_async_driver.select_value(
                f"INSERT INTO fixture_resync.{table} (name) VALUES ('next') RETURNING id"
            )
            assert new_id == 6
        empty_id = await asyncpg_async_driver.select_value(
            "INSERT INTO fixture_resync.empty_items (name) VALUES ('first') RETURNING id"
        )
        assert empty_id == 1
    finally:
        await asyncpg_async_driver.execute_script(TEARDOWN_SQL)


def test_resync_sequences_sync(psycopg_sync_config: "PsycopgSyncConfig", tmp_path: Path) -> None:
    """The sync loader resyncs serial and identity sequences."""
    _write_fixtures(tmp_path)
    with psycopg_sync_config.provide_session() as driver:
        driver.execute_script(SETUP_SQL)
        try:
            load_table_fixtures_sync(driver, tmp_path, tables=TABLES, resync_sequences=True)

            for table in ("serial_items", "identity_items"):
                new_id = driver.select_value(f"INSERT INTO fixture_resync.{table} (name) VALUES ('next') RETURNING id")
                assert new_id == 6
            assert (
                driver.select_value("INSERT INTO fixture_resync.empty_items (name) VALUES ('first') RETURNING id") == 1
            )
        finally:
            driver.execute_script(TEARDOWN_SQL)
