"""Profile analysis script for sqlspec benchmark profiles.

Reads .prof files generated by ``bench.py --profile`` and produces detailed
analysis tables showing where time is spent.

Usage::

    uv run python tools/scripts/analyze_profile.py tools/scripts/profiles/sqlite_sqlspec_iterative_inserts.prof
    uv run python tools/scripts/analyze_profile.py tools/scripts/profiles/  # analyze all profiles in directory
"""

import pstats
import sys
from pathlib import Path
from typing import Any

import click
from rich.console import Console
from rich.table import Table

__all__ = ("analyze_profile", "main")


def _load_stats(prof_path: Path) -> pstats.Stats:
    """Load a .prof file into a pstats.Stats object.

    Args:
        prof_path: Path to the .prof file.

    Returns:
        pstats.Stats object.
    """
    return pstats.Stats(str(prof_path))


def _extract_stats_entries(stats: pstats.Stats, sort_key: str = "cumulative", limit: int = 20) -> list[dict[str, Any]]:
    """Extract stats entries sorted by the given key.

    Args:
        stats: pstats.Stats object.
        sort_key: Sort key (cumulative, calls, tottime, etc.).
        limit: Maximum number of entries to return.

    Returns:
        List of dicts with function info and timing data.
    """
    stats.sort_stats(sort_key)
    entries: list[dict[str, Any]] = []

    # stats.stats is a dict of (filename, lineno, funcname) -> (cc, nc, tt, ct, callers)
    # cc = primitive call count, nc = total call count, tt = total time, ct = cumulative time
    sorted_keys = sorted(
        stats.stats.keys(),
        key=lambda k: stats.stats[k][3] if sort_key == "cumulative" else stats.stats[k][1],
        reverse=True,
    )

    for key in sorted_keys[:limit]:
        filename, lineno, funcname = key
        cc, nc, tt, ct, _callers = stats.stats[key]
        entries.append({
            "filename": filename,
            "lineno": lineno,
            "funcname": funcname,
            "ncalls": nc,
            "pcalls": cc,
            "tottime": tt,
            "cumtime": ct,
            "percall_tot": tt / nc if nc > 0 else 0,
            "percall_cum": ct / cc if cc > 0 else 0,
        })

    return entries


def _print_top_by_cumtime(stats: pstats.Stats, console: Console, limit: int = 20) -> None:
    """Print top functions by cumulative time.

    Args:
        stats: pstats.Stats object.
        console: Rich console for output.
        limit: Number of functions to show.
    """
    entries = _extract_stats_entries(stats, sort_key="cumulative", limit=limit)

    table = Table(title=f"Top {limit} Functions by Cumulative Time")
    table.add_column("#", justify="right", style="dim", width=4)
    table.add_column("Function", style="cyan", max_width=60)
    table.add_column("ncalls", justify="right", style="yellow")
    table.add_column("tottime (s)", justify="right", style="green")
    table.add_column("cumtime (s)", justify="right", style="magenta")
    table.add_column("per call (us)", justify="right", style="red")

    for i, entry in enumerate(entries, 1):
        func_display = f"{entry['filename']}:{entry['lineno']}({entry['funcname']})"
        ncalls_str = str(entry["ncalls"])
        if entry["pcalls"] != entry["ncalls"]:
            ncalls_str = f"{entry['ncalls']}/{entry['pcalls']}"

        table.add_row(
            str(i),
            func_display,
            ncalls_str,
            f"{entry['tottime']:.6f}",
            f"{entry['cumtime']:.6f}",
            f"{entry['percall_cum'] * 1_000_000:.2f}",
        )

    console.print(table)


def _print_top_by_calls(stats: pstats.Stats, console: Console, limit: int = 20) -> None:
    """Print top functions by call count.

    Args:
        stats: pstats.Stats object.
        console: Rich console for output.
        limit: Number of functions to show.
    """
    # Sort by call count (nc field = index 1)
    sorted_keys = sorted(stats.stats.keys(), key=lambda k: stats.stats[k][1], reverse=True)

    table = Table(title=f"Top {limit} Functions by Call Count")
    table.add_column("#", justify="right", style="dim", width=4)
    table.add_column("Function", style="cyan", max_width=60)
    table.add_column("ncalls", justify="right", style="yellow")
    table.add_column("tottime (s)", justify="right", style="green")
    table.add_column("cumtime (s)", justify="right", style="magenta")
    table.add_column("time/call (us)", justify="right", style="red")

    for i, key in enumerate(sorted_keys[:limit], 1):
        filename, lineno, funcname = key
        cc, nc, tt, ct, _callers = stats.stats[key]
        func_display = f"{filename}:{lineno}({funcname})"
        ncalls_str = str(nc)
        if cc != nc:
            ncalls_str = f"{nc}/{cc}"
        per_call = (tt / nc * 1_000_000) if nc > 0 else 0

        table.add_row(str(i), func_display, ncalls_str, f"{tt:.6f}", f"{ct:.6f}", f"{per_call:.2f}")

    console.print(table)


def _print_per_execute_summary(stats: pstats.Stats, console: Console) -> None:
    """Print per-execute() call count analysis.

    Finds execute-related functions and shows how many times each internal
    function is called per top-level execute() invocation.

    Args:
        stats: pstats.Stats object.
        console: Rich console for output.
    """
    # Find the top-level execute call count
    execute_count = 0
    for (filename, _lineno, funcname), (_cc, nc, _tt, _ct, _callers) in stats.stats.items():
        # Match common execute entry points
        if funcname in ("execute", "dispatch_statement_execution") and "driver" in filename:
            execute_count = max(execute_count, nc)

    if execute_count == 0:
        # Try broader matching
        for (_filename, _lineno, funcname), (_cc, nc, _tt, _ct, _callers) in stats.stats.items():
            if funcname == "execute":
                execute_count = max(execute_count, nc)

    if execute_count == 0:
        console.print("[yellow]Could not determine execute() call count for per-call analysis[/yellow]")
        return

    console.print(f"\n[bold]Per-execute() call counts[/bold] (based on {execute_count} execute() calls)")

    # Show interesting internal functions and their calls-per-execute ratio
    interesting_patterns = [
        "compile",
        "dispatch",
        "with_cursor",
        "build_statement_result",
        "prepare_driver_parameters",
        "_format_parameter_set",
        "_qc_prepare",
        "_qc_lookup",
        "_qc_build",
        "_qc_execute",
        "_qc_store",
        "process_parameters",
        "execute",
        "cursor",
    ]

    table = Table(title="Internal Function Calls per execute()")
    table.add_column("Function", style="cyan", max_width=60)
    table.add_column("Total Calls", justify="right", style="yellow")
    table.add_column("Calls/execute", justify="right", style="magenta")
    table.add_column("Time/call (us)", justify="right", style="green")

    entries: list[tuple[str, int, float, float]] = []
    for (filename, lineno, funcname), (_cc, nc, tt, _ct, _callers) in stats.stats.items():
        if any(pat in funcname.lower() for pat in interesting_patterns):
            func_display = f"{filename}:{lineno}({funcname})"
            per_call_us = (tt / nc * 1_000_000) if nc > 0 else 0
            entries.append((func_display, nc, nc / execute_count, per_call_us))

    # Sort by calls per execute descending
    entries.sort(key=lambda x: x[1], reverse=True)

    for func_display, total_calls, calls_per_exec, per_call_us in entries[:30]:
        table.add_row(func_display, str(total_calls), f"{calls_per_exec:.1f}", f"{per_call_us:.2f}")

    console.print(table)


def analyze_profile(prof_path: Path, console: Console) -> None:
    """Analyze a single .prof file.

    Args:
        prof_path: Path to the .prof file.
        console: Rich console for output.
    """
    console.print(f"\n[bold]{'=' * 70}[/bold]")
    console.print(f"[bold]Analyzing: {prof_path.name}[/bold]")
    console.print(f"[bold]{'=' * 70}[/bold]\n")

    stats = _load_stats(prof_path)
    stats.strip_dirs()

    # Total time summary
    total_time = 0.0
    total_calls = 0
    for _cc, nc, tt, _ct, _callers in stats.stats.values():
        total_time += tt
        total_calls += nc

    console.print(f"  Total time: {total_time:.4f}s")
    console.print(f"  Total function calls: {total_calls:,}")
    console.print()

    _print_top_by_cumtime(stats, console)
    console.print()
    _print_top_by_calls(stats, console)
    console.print()
    _print_per_execute_summary(stats, console)


@click.command()
@click.argument("path", type=click.Path(exists=True))
@click.option("--top", default=20, show_default=True, help="Number of top functions to display")
def main(path: str, top: int) -> None:
    """Analyze cProfile .prof files from sqlspec benchmarks.

    PATH can be a single .prof file or a directory containing .prof files.
    """
    console = Console()
    target = Path(path)

    if target.is_file():
        if target.suffix != ".prof":
            click.secho(f"Error: {target} is not a .prof file", fg="red")
            sys.exit(1)
        analyze_profile(target, console)
    elif target.is_dir():
        prof_files = sorted(target.glob("*.prof"))
        if not prof_files:
            click.secho(f"No .prof files found in {target}", fg="yellow")
            sys.exit(1)
        click.echo(f"Found {len(prof_files)} profile(s) in {target}")
        for prof_file in prof_files:
            analyze_profile(prof_file, console)
    else:
        click.secho(f"Error: {target} is not a file or directory", fg="red")
        sys.exit(1)

    console.print()
    click.secho("Analysis complete.", fg="green")


if __name__ == "__main__":
    main()
