"""Integration test for the route-handler-deepcopy crash reported against 0.48.1.

The original report comes from a Litestar Controller path:

    Controller.get_route_handlers() → deepcopy(self_handler)
        → walks handler.dependencies → reaches mypyc-compiled _*FilterProvider
        → TypeError: __init__() missing required argument

The underlying public-API failure is `copy.deepcopy` on any Litestar route
handler whose `dependencies` dict contains providers generated by
`create_filter_dependencies`. This test exercises that path through `Litestar`
+ `app.routes`, which is the smallest reproduction not reliant on a downstream
plugin pre-attaching dependencies.
"""

import copy
from typing import Any

import pytest
from litestar import Litestar, get

from sqlspec.extensions.litestar.providers import (
    FieldNameType,
    create_filter_dependencies,
    dep_cache,
)
from sqlspec.typing import LITESTAR_INSTALLED

if not LITESTAR_INSTALLED:
    pytest.skip("Litestar not installed", allow_module_level=True)


@pytest.fixture(autouse=True)
def _clear_dependency_cache() -> Any:
    dep_cache.dependencies.clear()
    yield
    dep_cache.dependencies.clear()


def _route_handler(app: "Litestar", path: str) -> Any:
    for route in app.routes:
        if route.path != path:
            continue
        if hasattr(route, "route_handler"):
            return route.route_handler
        handlers = getattr(route, "route_handlers", None)
        if handlers:
            return handlers[0]
    msg = f"route {path!r} not registered on app"
    raise AssertionError(msg)


def test_handler_deepcopy_with_limit_offset_filter() -> None:
    """Minimum repro: a handler with a single LimitOffsetFilter dep must deepcopy."""
    deps = create_filter_dependencies({"pagination_type": "limit_offset", "pagination_size": 10})

    @get("/probe", dependencies=deps)
    async def probe() -> "list[Any]":
        return []

    app = Litestar(route_handlers=[probe])
    handler = _route_handler(app, "/probe")

    out = copy.deepcopy(handler)
    assert out is not handler


def test_handler_deepcopy_with_full_filter_set() -> None:
    """Every supported filter type wired in. Each `_*FilterProvider` must survive deepcopy."""
    deps = create_filter_dependencies(
        {
            "id_filter": int,
            "id_field": "id",
            "pagination_type": "limit_offset",
            "pagination_size": 25,
            "search": "name",
            "search_ignore_case": False,
            "sort_field": "id",
            "created_at": True,
            "updated_at": True,
            "in_fields": [FieldNameType("name", str)],
            "not_in_fields": [FieldNameType("name", str)],
            "null_fields": "deleted_at",
            "not_null_fields": "created_at",
        }
    )

    @get("/probe", dependencies=deps)
    async def probe() -> "list[Any]":
        return []

    app = Litestar(route_handlers=[probe])
    handler = _route_handler(app, "/probe")

    out = copy.deepcopy(handler)
    assert out is not handler
    assert set(out.dependencies) == set(handler.dependencies)


def test_handler_repeated_deepcopy_is_idempotent() -> None:
    """A deepcopied handler must itself deepcopy — guards the Controller registration path."""
    deps = create_filter_dependencies({"pagination_type": "limit_offset"})

    @get("/probe", dependencies=deps)
    async def probe() -> "list[Any]":
        return []

    app = Litestar(route_handlers=[probe])
    handler = _route_handler(app, "/probe")

    first = copy.deepcopy(handler)
    second = copy.deepcopy(first)
    assert second is not first
