"""IBM Db2 adapter for SQLSpec."""

from sqlspec.adapters.db2._typing import (
    IBM_DB_DBI_INSTALLED,
    IBM_DB_INSTALLED,
    Db2Connection,
    Db2ConnectionProtocol,
    Db2Cursor,
    Db2CursorProtocol,
    Db2Error,
    Db2QueryParams,
    Db2RawCursor,
    Db2SessionContext,
)
from sqlspec.adapters.db2.core import (
    apply_driver_features,
    build_connection_config,
    build_dsn_string,
    build_insert_statement,
    build_profile,
    build_statement_config,
    collect_rows,
    create_mapped_exception,
    default_statement_config,
    driver_profile,
    format_identifier,
    normalize_execute_many_parameters,
    normalize_execute_parameters,
    resolve_column_names,
    resolve_many_rowcount,
    resolve_rowcount,
)

__all__ = (
    "IBM_DB_DBI_INSTALLED",
    "IBM_DB_INSTALLED",
    "Db2Connection",
    "Db2ConnectionProtocol",
    "Db2Cursor",
    "Db2CursorProtocol",
    "Db2Error",
    "Db2QueryParams",
    "Db2RawCursor",
    "Db2SessionContext",
    "apply_driver_features",
    "build_connection_config",
    "build_dsn_string",
    "build_insert_statement",
    "build_profile",
    "build_statement_config",
    "collect_rows",
    "create_mapped_exception",
    "default_statement_config",
    "driver_profile",
    "format_identifier",
    "normalize_execute_many_parameters",
    "normalize_execute_parameters",
    "resolve_column_names",
    "resolve_many_rowcount",
    "resolve_rowcount",
)
