"""SQLSpec Core Module - SQL Processing Infrastructure.

This module provides the core SQL compilation, parameter processing,
caching, and result management layer for SQLSpec.

Responsibilities:
    - statement: SQL statement encapsulation, configuration, and execution state.
    - parameters: Parameter extraction, validation, coercion, and style conversion.
    - compiler: Dialect translation, AST analysis, and SQLGlot compilation.
    - result: Query execution result encapsulation and Arrow integration.
    - filters: Composable query filters and pagination.
    - cache: Statement, expression, and compilation caching.
    - splitter: Dialect-aware SQL script splitting.
    - hashing: Cache key hashing for statements and expressions.

Example Usage:
    >>> from sqlspec.core import SQL, StatementConfig
    >>> config = StatementConfig(dialect="postgresql")
    >>> stmt = SQL(
    ...     "SELECT * FROM users WHERE id = :id",
    ...     {"id": 1},
    ...     statement_config=config,
    ... )
    >>> compiled_sql, params = stmt.compile()
"""

from sqlspec.core import filters
from sqlspec.core._cursor import register_cursor_type
from sqlspec.core._ordering import NullsPlacement, apply_direction, default_nulls, ordered
from sqlspec.core._pagination import CursorPagination, OffsetPagination, Pagination
from sqlspec.core.cache import (
    CacheConfig,
    CachedStatement,
    CacheKey,
    CacheStats,
    FiltersView,
    LRUCache,
    NamespacedCache,
    clear_all_caches,
    create_cache_key,
    get_cache,
    get_cache_config,
    get_cache_statistics,
    get_default_cache,
    get_pipeline_metrics,
    log_cache_stats,
    reset_pipeline_registry,
    reset_stats_only,
    update_cache_config,
)
from sqlspec.core.capabilities import TypeCoercionCapabilities
from sqlspec.core.compiler import (
    CompiledSQL,
    OperationProfile,
    OperationType,
    SQLProcessor,
    is_copy_from_operation,
    is_copy_operation,
    is_copy_to_operation,
)
from sqlspec.core.correlation import CorrelationExtractor
from sqlspec.core.explain import ExplainFormat, ExplainOptions
from sqlspec.core.filters import (
    AnyCollectionFilter,
    BeforeAfterFilter,
    BooleanFilter,
    ChoicesFilter,
    CursorFilter,
    CursorKey,
    CursorKeys,
    FilterTypes,
    FilterTypeT,
    InCollectionFilter,
    LimitOffsetFilter,
    NotInCollectionFilter,
    NotNullFilter,
    NullFilter,
    OrderByFilter,
    SearchFilter,
    StatementFilter,
    apply_filter,
    canonicalize_filters,
    normalize_cursor_keys,
)
from sqlspec.core.hashing import (
    hash_expression,
    hash_expression_node,
    hash_filters,
    hash_optimized_expression,
    hash_parameters,
    hash_sql_statement,
)
from sqlspec.core.metrics import StackExecutionMetrics
from sqlspec.core.parameters import (
    DRIVER_PARAMETER_PROFILES,
    EXECUTE_MANY_MIN_ROWS,
    PARAMETER_REGEX,
    DriverParameterProfile,
    ParameterConverter,
    ParameterDeclaration,
    ParameterInfo,
    ParameterProcessingResult,
    ParameterProcessor,
    ParameterProfile,
    ParameterStyle,
    ParameterStyleConfig,
    ParameterValidator,
    ParamTypeMatcher,
    TypedParameter,
    build_literal_inlining_transform,
    build_null_pruning_transform,
    build_statement_config_from_profile,
    collect_null_parameter_ordinals,
    get_driver_profile,
    is_iterable_parameters,
    looks_like_execute_many,
    matches_param_type,
    normalize_parameter_key,
    register_driver_profile,
    register_param_type,
    replace_null_parameters_with_literals,
    replace_placeholders_with_literals,
    resolve_param_type,
    validate_parameter_alignment,
    wrap_with_type,
)
from sqlspec.core.query_modifiers import (
    ConditionFactory,
    apply_limit,
    apply_offset,
    apply_or_where,
    apply_select_only,
    apply_where,
    create_between_condition,
    create_condition,
    create_exists_condition,
    create_in_condition,
    create_not_exists_condition,
    create_not_in_condition,
    expr_eq,
    expr_gt,
    expr_gte,
    expr_ilike,
    expr_is_not_null,
    expr_is_null,
    expr_like,
    expr_lt,
    expr_lte,
    expr_neq,
    expr_not_like,
    extract_column_name,
    parse_column_for_condition,
    safe_modify_with_cte,
)
from sqlspec.core.result import (
    ArrowResult,
    DMLResult,
    SQLResult,
    StackResult,
    StatementResult,
    build_arrow_result_from_reader,
    build_arrow_result_from_table,
    create_arrow_result,
    create_sql_result,
)
from sqlspec.core.splitter import split_sql_script
from sqlspec.core.stack import StackOperation, StatementStack
from sqlspec.core.statement import (
    SQL,
    ProcessedState,
    Statement,
    StatementConfig,
    get_default_config,
    get_default_parameter_config,
)
from sqlspec.core.type_converter import (
    BaseInputConverter,
    convert_decimal,
    convert_iso_date,
    convert_iso_datetime,
    convert_iso_time,
    convert_json,
    convert_uuid,
    format_datetime_rfc3339,
    parse_datetime_rfc3339,
)
from sqlspec.exceptions import StackExecutionError

__all__ = (
    "DRIVER_PARAMETER_PROFILES",
    "EXECUTE_MANY_MIN_ROWS",
    "PARAMETER_REGEX",
    "SQL",
    "AnyCollectionFilter",
    "ArrowResult",
    "BaseInputConverter",
    "BeforeAfterFilter",
    "BooleanFilter",
    "CacheConfig",
    "CacheKey",
    "CacheStats",
    "CachedStatement",
    "ChoicesFilter",
    "CompiledSQL",
    "ConditionFactory",
    "CorrelationExtractor",
    "CursorFilter",
    "CursorKey",
    "CursorKeys",
    "CursorPagination",
    "DMLResult",
    "DriverParameterProfile",
    "ExplainFormat",
    "ExplainOptions",
    "FilterTypeT",
    "FilterTypes",
    "FiltersView",
    "InCollectionFilter",
    "LRUCache",
    "LimitOffsetFilter",
    "NamespacedCache",
    "NotInCollectionFilter",
    "NotNullFilter",
    "NullFilter",
    "NullsPlacement",
    "OffsetPagination",
    "OperationProfile",
    "OperationType",
    "OrderByFilter",
    "Pagination",
    "ParamTypeMatcher",
    "ParameterConverter",
    "ParameterDeclaration",
    "ParameterInfo",
    "ParameterProcessingResult",
    "ParameterProcessor",
    "ParameterProfile",
    "ParameterStyle",
    "ParameterStyleConfig",
    "ParameterValidator",
    "ProcessedState",
    "SQLProcessor",
    "SQLResult",
    "SearchFilter",
    "StackExecutionError",
    "StackExecutionMetrics",
    "StackOperation",
    "StackResult",
    "Statement",
    "StatementConfig",
    "StatementFilter",
    "StatementResult",
    "StatementStack",
    "TypeCoercionCapabilities",
    "TypedParameter",
    "apply_direction",
    "apply_filter",
    "apply_limit",
    "apply_offset",
    "apply_or_where",
    "apply_select_only",
    "apply_where",
    "build_arrow_result_from_reader",
    "build_arrow_result_from_table",
    "build_literal_inlining_transform",
    "build_null_pruning_transform",
    "build_statement_config_from_profile",
    "canonicalize_filters",
    "clear_all_caches",
    "collect_null_parameter_ordinals",
    "convert_decimal",
    "convert_iso_date",
    "convert_iso_datetime",
    "convert_iso_time",
    "convert_json",
    "convert_uuid",
    "create_arrow_result",
    "create_between_condition",
    "create_cache_key",
    "create_condition",
    "create_exists_condition",
    "create_in_condition",
    "create_not_exists_condition",
    "create_not_in_condition",
    "create_sql_result",
    "default_nulls",
    "expr_eq",
    "expr_gt",
    "expr_gte",
    "expr_ilike",
    "expr_is_not_null",
    "expr_is_null",
    "expr_like",
    "expr_lt",
    "expr_lte",
    "expr_neq",
    "expr_not_like",
    "extract_column_name",
    "filters",
    "format_datetime_rfc3339",
    "get_cache",
    "get_cache_config",
    "get_cache_statistics",
    "get_default_cache",
    "get_default_config",
    "get_default_parameter_config",
    "get_driver_profile",
    "get_pipeline_metrics",
    "hash_expression",
    "hash_expression_node",
    "hash_filters",
    "hash_optimized_expression",
    "hash_parameters",
    "hash_sql_statement",
    "is_copy_from_operation",
    "is_copy_operation",
    "is_copy_to_operation",
    "is_iterable_parameters",
    "log_cache_stats",
    "looks_like_execute_many",
    "matches_param_type",
    "normalize_cursor_keys",
    "normalize_parameter_key",
    "ordered",
    "parse_column_for_condition",
    "parse_datetime_rfc3339",
    "register_cursor_type",
    "register_driver_profile",
    "register_param_type",
    "replace_null_parameters_with_literals",
    "replace_placeholders_with_literals",
    "reset_pipeline_registry",
    "reset_stats_only",
    "resolve_param_type",
    "safe_modify_with_cte",
    "split_sql_script",
    "update_cache_config",
    "validate_parameter_alignment",
    "wrap_with_type",
)
