"""Unit tests for framework-neutral filter alias resolution."""

import pytest

from sqlspec.extensions import _filter_aliases
from sqlspec.extensions._filter_aliases import resolve_sort_field_aliases


def test_resolver_keeps_identity_aliases() -> None:
    """Internal sort fields remain valid inbound query values."""
    resolution = resolve_sort_field_aliases("created_at")

    assert resolution.default_field == "created_at"
    assert resolution.default_query_value == "createdAt"
    assert resolution.allowed_fields == frozenset({"created_at"})
    assert resolution.inbound_aliases["created_at"] == "created_at"
    assert resolution.inbound_aliases["createdAt"] == "created_at"
    assert resolution.normalize("created_at") == "created_at"
    assert resolution.allowed_display_names == ("createdAt",)


def test_resolver_accepts_explicit_alias() -> None:
    """Explicit wire aliases map back to configured internal fields."""
    resolution = resolve_sort_field_aliases(
        ["created_at", "uploaded_collections"], sort_field_aliases={"uploadedCollections": "uploaded_collections"}
    )

    assert resolution.inbound_aliases["uploadedCollections"] == "uploaded_collections"
    assert resolution.normalize("uploadedCollections") == "uploaded_collections"
    assert resolution.normalize("uploaded_collections") == "uploaded_collections"
    assert resolution.field_display_names["uploaded_collections"] == "uploadedCollections"
    assert resolution.allowed_display_names == ("createdAt", "uploadedCollections")


def test_resolver_generates_camel_aliases_by_default() -> None:
    """Camel aliases are generated by default for configured sort fields."""
    resolution = resolve_sort_field_aliases(["created_at", "uploaded_collections"])

    assert resolution.inbound_aliases["createdAt"] == "created_at"
    assert resolution.inbound_aliases["uploadedCollections"] == "uploaded_collections"
    assert resolution.normalize("createdAt") == "created_at"
    assert resolution.normalize("uploadedCollections") == "uploaded_collections"
    assert resolution.normalize("created_at") == "created_at"


def test_resolver_default_query_value_uses_display_alias() -> None:
    """The default query value uses the display alias by default."""
    resolution = resolve_sort_field_aliases(["created_at", "uploaded_collections"])

    assert resolution.default_field == "created_at"
    assert resolution.default_query_value == "createdAt"
    assert resolution.field_display_names["created_at"] == "createdAt"
    assert resolution.allowed_display_names == ("createdAt", "uploadedCollections")


def test_resolver_rejects_alias_to_unknown_sort_field() -> None:
    """Aliases cannot target fields outside the configured sort allowlist."""
    with pytest.raises(ValueError, match="unknown sort field"):
        resolve_sort_field_aliases(["created_at"], sort_field_aliases={"uploadedCollections": "uploaded_collections"})


def test_resolver_rejects_collision_to_different_fields() -> None:
    """One inbound alias cannot normalize to multiple internal fields."""
    with pytest.raises(ValueError, match="ambiguous sort field alias"):
        resolve_sort_field_aliases(
            ["created_at", "uploaded_collections"],
            sort_field_aliases={"createdAt": "uploaded_collections"},
            sort_field_camelize=True,
        )


def test_resolver_can_disable_camel_aliases() -> None:
    """Camel aliases can be disabled for snake_case-only contracts."""
    resolution = resolve_sort_field_aliases(["created_at", "uploaded_collections"], sort_field_camelize=False)

    assert resolution.default_query_value == "created_at"
    assert resolution.normalize("created_at") == "created_at"
    assert resolution.normalize("createdAt") is None
    assert resolution.allowed_display_names == ("created_at", "uploaded_collections")


def test_resolver_handles_dotted_fields() -> None:
    """Qualified dotted fields keep identity support and gain dotted camel aliases."""
    resolution = resolve_sort_field_aliases(["p.created_at", "p.name"])

    assert resolution.inbound_aliases["p.created_at"] == "p.created_at"
    assert resolution.inbound_aliases["p.createdAt"] == "p.created_at"
    assert resolution.normalize("p.createdAt") == "p.created_at"
    assert resolution.allowed_display_names == ("p.createdAt", "p.name")


def test_resolver_normalize_uses_precomputed_alias_map(monkeypatch: pytest.MonkeyPatch) -> None:
    """Normalization uses a dictionary lookup after provider creation."""
    resolution = resolve_sort_field_aliases(["created_at", "uploaded_collections"])

    def fail_camelize(_: str) -> str:
        pytest.fail("normalize() must not camelize values at request time")

    monkeypatch.setattr(_filter_aliases, "camelize", fail_camelize)

    assert resolution.normalize("createdAt") == "created_at"
    assert resolution.normalize("uploadedCollections") == "uploaded_collections"
    assert resolution.normalize("unknownField") is None


def test_provider_hashes_include_alias_config_fields() -> None:
    """Existing provider cache keys distinguish the new alias configuration fields."""
    pytest.importorskip("fastapi")
    pytest.importorskip("litestar")
    from sqlspec.extensions.fastapi.providers import _make_hashable as fastapi_make_hashable
    from sqlspec.extensions.litestar.providers import _make_hashable as litestar_make_hashable

    base_config = {"sort_field": ["created_at", "uploaded_collections"]}
    explicit_alias_config = {
        "sort_field": ["created_at", "uploaded_collections"],
        "sort_field_aliases": {"uploadedCollections": "uploaded_collections"},
    }
    camel_alias_config = {"sort_field": ["created_at", "uploaded_collections"], "sort_field_camelize": True}

    for make_hashable in (fastapi_make_hashable, litestar_make_hashable):
        assert make_hashable(base_config) != make_hashable(explicit_alias_config)
        assert make_hashable(base_config) != make_hashable(camel_alias_config)
        assert make_hashable(explicit_alias_config) != make_hashable(camel_alias_config)
