name: Documentation Build

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build documentation
        run: uv run python tools/build_docs.py docs-build

      - name: Package documentation artifact
        run: tar -czvf docs-build.tar.gz docs-build

      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./docs-build.tar.gz
          asset_name: docs-build-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload 'latest' docs artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: latest-docs
          path: docs-build.tar.gz
